modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
modId="randomadditionsraph" #mandatory
version="0.1.0" #mandatory
displayName="Random Additions" #mandatory
credits="Thanks for forge" #optional
authors="Raph" #optional
description='''
This is my mod
By Raph
'''
[[dependencies.randomadditionsraph]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.randomadditionsraph]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"